spring.application.name=user-service
server.port=8081
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//5508.axzt.top:60057/XEPDB1
spring.datasource.username=my_user
spring.datasource.password=205043
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
jwt.secret=hddhddhddhddhddhddhddhddhddhddhdd
jwt.expiration=604800000
spring.kafka.bootstrap-servers=5508.axzt.top:60150
# Nacos 已移除