spring.application.name=log-service
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=log-group
spring.cloud.nacos.discovery.server-addr=localhost:8848
spring.cloud.nacos.discovery.username=nacos
spring.cloud.nacos.discovery.password=nacos
server.port=8083