spring.application.name=studysys
server.port=8080
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//5508.axzt.top:60057/XEPDB1
spring.datasource.username=my_user
spring.datasource.password=205043
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
spring.data.redis.host=5508.axzt.top
spring.data.redis.port=60252
spring.kafka.bootstrap-servers=5508.axzt.top:60150
# Nacos 已移除